---

- include: dependencies.yml

- include: entry.yml
  vars:
    dn: "{{ entry.key }}"
    objectClass: "{{ entry.value.objectClass }}"
    attributes: "{{ entry.value }}"
  loop: "{{ openldap.entries | dict2items }}"
  loop_control:
    loop_var: entry
