---

- name: initialize configuration
  become: yes
  become_user: ldap
  command:
    cmd: slapadd -F /etc/openldap/slapd.d -n 0
    stdin: |
      dn: cn=config
      objectClass: olcGlobal
      cn: config
      olcPidFile: /var/run/openldap/slapd.pid

      dn: cn=schema,cn=config
      objectClass: olcSchemaConfig
      cn: schema

      include: file:///etc/openldap/schema/core.ldif

      dn: olcDatabase={-1}frontend,cn=config
      objectClass: olcDatabaseConfig
      olcDatabase: {-1}frontend

      dn: olcDatabase={0}config,cn=config
      objectClass: olcDatabaseConfig
      olcDatabase: {0}config
      olcAccess: {0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage by * none
    creates: /etc/openldap/slapd.d/cn=config.ldif
