---

- name: "{{ dn }}"
  ldap_entry:
    dn: "{{ dn }}"
    objectClass: "{{ objectClass }}"
    attributes: "{{ attributes }}"

- name: "{{ dn }} attributes"
  ldap_attr:
    state: exact
    dn: "{{ dn }}"
    name: "{{ attr.key }}"
    values: "{{ attr.value }}"
  loop: "{{ attributes | dict2items }}"
  loop_control:
    loop_var: attr
