---

- name: get credential
  set_fact:
    credential: '{{ item.value }}'
  when: dn is regex('.*'~item.key)
  loop: "{{ openldap.credentials | default({}) | dict2items }}"
  no_log: true

- name: "{{ dn }}"
  ldap_entry:
    dn: "{{ dn }}"
    objectClass: "{{ objectClass }}"
    attributes: "{{ attributes }}"
  args:
    server_uri: '{{ credential.server_uri }}'
    bind_dn: '{{ credential.bind_dn }}'
    bind_pw: '{{ credential.bind_pw }}'

- name: "{{ dn }} attributes"
  ldap_attrs:
    dn: "{{ dn }}"
    attributes: "{{ attributes }}"
    state: exact
  args:
    server_uri: '{{ credential.server_uri }}'
    bind_dn: '{{ credential.bind_dn }}'
    bind_pw: '{{ credential.bind_pw }}'
