---

- include: map.yml

- include: dependencies.yml

- name: enable PowerTools repository
  ini_file:
    dest: "/etc/yum.repos.d/{{ ansible_distribution }}-PowerTools.repo"
    section: PowerTools
    option: enabled
    value: "1"
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

- name: install
  package:
    name: "{{ openldap.packages }}"
    state: present

- name: enable and start
  service:
    name: "{{ openldap.service_name }}"
    state: started
    enabled: yes

- include: entry.yml
  vars:
    dn: "olcDatabase={-1}frontend,cn=config"
    objectClass:
      - olcDatabaseConfig
    attributes:
      olcDatabase: "{-1}frontend"

- include: entry.yml
  vars:
    dn: "olcDatabase={0}config,cn=config"
    objectClass:
      - olcDatabaseConfig
    attributes:
      olcDatabase: "{0}config"
      olcAccess: '{0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage by * none'

- include: entry.yml
  vars:
    dn: "olcDatabase={1}monitor,cn=config"
    objectClass:
      - olcDatabaseConfig
    attributes:
      olcDatabase: "{1}monitor"
      olcAccess: '{0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" read by * none'

- include: entry.yml
  vars:
    dn: "olcDatabase={2}mdb,cn=config"
    objectClass:
      - olcDatabaseConfig
      - olcMdbConfig
    attributes:
      olcDatabase: "{2}mdb"
      olcSuffix: dc=example,dc=com
      olcRootDN: cn=Manager,dc=example,dc=com
      olcRootPW: password
      olcDbDirectory: /var/lib/ldap
