---

openldap:
  ansible_dependencies: python-ldap
  packages:
  service_name: slapd
  entries:
    "olcDatabase={-1}frontend,cn=config":
        objectClass: olcDatabaseConfig
        olcDatabase: "{-1}frontend"
    'olcDatabase={0}config,cn=config':
        objectClass: olcDatabaseConfig
        olcDatabase: "{0}config"
        olcAccess: '{0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage by * none'
