---

openldap:
  ansible_dependencies: python-ldap
  packages:
  service_name: slapd
  credentials:
    cn=config:
      server_uri: ldap://127.0.0.1:389
      bind_dn: cn=admin,cn=config
      bind_pw: changeme
  entries:
    olcDatabase={-1}frontend,cn=config:
      objectClass:
        - olcDatabaseConfig
        - olcFrontendConfig
      olcDatabase: '{-1}frontend'
    olcDatabase={0}config,cn=config:
      objectClass: olcDatabaseConfig
      olcDatabase: '{0}config'
      olcAccess: '{0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage by * none'
      olcRootDN: cn=admin,cn=config
      olcRootPW: '{SSHA}MobwKIUz0genUZKgynwDnRFiz9cYRN93'
